# Generated by Django 4.1.7 on 2023-03-30 09:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attack",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING_FOR_DATA", "Waiting For Data"),
                            ("PENDING", "Pending"),
                            ("READY", "Ready"),
                            ("ONGOING", "Ongoing"),
                            ("EXPIRED", "Expired"),
                            ("SUCCESS", "Success"),
                        ],
                        default="WAITING_FOR_DATA",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "attack_service_attacks",
            },
        ),
        migrations.CreateModel(
            name="Objective",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("begins_at", models.DateTimeField(db_index=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("org_id", models.CharField(db_index=True, max_length=120)),
                (
                    "goal",
                    models.CharField(
                        choices=[("TARGET_CLICKED_ON_LINK", "Target Clicked On Link")],
                        db_index=True,
                        default="TARGET_CLICKED_ON_LINK",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "db_table": "attack_service_objectives",
            },
        ),
        migrations.CreateModel(
            name="PhishingEmail",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("sender", models.CharField(max_length=200)),
                (
                    "recipients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), size=None
                    ),
                ),
                ("body", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttackLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.CharField(max_length=200)),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "attack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.attack"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttackActionable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content_id", models.CharField(max_length=20)),
                (
                    "attack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.attack"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attack",
            name="objective",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.objective"
            ),
        ),
    ]
