# Generated by Django 4.1.7 on 2023-03-30 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="attackactionable",
            table="attack_service_attack_actionables",
        ),
        migrations.AlterModelTable(
            name="phishingemail",
            table="attack_service_phishing_emails",
        ),
    ]
