# Generated by Django 4.1.7 on 2023-03-30 11:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_attackactionable_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhishingToken",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=200, unique=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "attack_service_phishing_tokens",
            },
        ),
    ]
