# Generated by Django 4.1.7 on 2023-03-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_phishingtoken"),
        ("core", "0003_rename_type_attackactionable_content_type_and_more"),
    ]

    operations = []
