# Generated by Django 4.1.7 on 2023-03-30 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_type_attackactionable_content_type_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="attacklog",
            table="attack_service_attack_logs",
        ),
    ]
