# Generated by Django 4.1.7 on 2023-03-31 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_attacklog_table"),
        ("core", "0004_merge_20230330_1216"),
    ]

    operations = []
