# Generated by Django 4.1.7 on 2023-03-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_merge_20230331_1014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objective",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="objective",
            name="org_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterModelTable(
            name="attacklog",
            table=None,
        ),
    ]
