# Generated by Django 4.1.7 on 2023-03-31 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_objective_id_alter_objective_org_id_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="attacklog",
            table="attack_service_attack_logs",
        ),
    ]
