# Generated by Django 4.1.7 on 2023-03-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_objective_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attacklog",
            name="message",
        ),
        migrations.AddField(
            model_name="attacklog",
            name="type",
            field=models.CharField(
                choices=[
                    ("EMAIL_SENT", "Email Sent"),
                    ("LINK_CLICKED", "Link Clicked"),
                ],
                default="EMAIL_SENT",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
