# Generated by Django 4.1.7 on 2023-03-31 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_attacklog_message_attacklog_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="phishingtoken",
            name="attack",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.attack"
            ),
        ),
    ]
