# Generated by Django 4.1.7 on 2023-04-03 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_objective_id"),
        ("core", "0007_alter_attacklog_table"),
    ]

    operations = []
