# Generated by Django 4.1.7 on 2023-03-31 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_attacklog_table"),
        ("core", "0008_phishingtoken_attack"),
    ]

    operations = []
