# Generated by Django 4.1.7 on 2023-04-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_attackartifact_remove_phishingtoken_attack_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phishingemail",
            name="is_html",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="phishingemail",
            name="token",
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
