# Generated by Django 4.1.7 on 2023-04-03 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0012_alter_attackartifact_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phishingemail",
            name="token",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=200,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attackartifact",
            unique_together={("content_type", "object_id")},
        ),
        migrations.AddIndex(
            model_name="attackartifact",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="attack_serv_content_56c1ce_idx",
            ),
        ),
    ]
