# Generated by Django 4.1.7 on 2023-04-03 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_merge_20230403_2003"),
        ("core", "0013_alter_phishingemail_token_and_more"),
    ]

    operations = []
