# Generated by Django 4.1.7 on 2023-04-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_remove_phishingemail_sent_at_attackartifact_sent_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phishingemail",
            name="is_draft",
        ),
        migrations.AddField(
            model_name="phishingemail",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("IS_DELIVERABLE", "Is Deliverable"),
                    ("SENT", "Sent"),
                    ("OPENED", "Opened"),
                    ("LINK_CLICKED", "Link Clicked"),
                ],
                default="DRAFT",
                max_length=200,
            ),
        ),
    ]
