# Generated by Django 4.1.7 on 2023-04-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_remove_phishingemail_is_draft_phishingemail_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phishingemail",
            name="status",
        ),
        migrations.AddField(
            model_name="attackartifact",
            name="status",
            field=models.CharField(
                choices=[("UNDER_REVIEW", "Under Review"), ("APPROVED", "Approved")],
                default="UNDER_REVIEW",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="attack",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING_FOR_DATA", "Waiting For Data"),
                    ("ONGOING", "Ongoing"),
                    ("FAILED", "Failed"),
                    ("SUCCESS", "Success"),
                ],
                default="WAITING_FOR_DATA",
                max_length=20,
            ),
        ),
    ]
