# Generated by Django 4.1.7 on 2023-04-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_remove_phishingemail_status_attackartifact_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attacklog",
            name="type",
            field=models.CharField(
                choices=[
                    ("EMAIL_SENT", "Email Sent"),
                    ("EMAIL_OPENED", "Email Opened"),
                    ("LINK_CLICKED", "Link Clicked"),
                ],
                max_length=200,
            ),
        ),
    ]
