# Generated by Django 4.1.7 on 2023-04-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_attacklog_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="objective",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("ONGOING", "Ongoing"),
                    ("EXPIRED", "Expired"),
                ],
                default="CREATED",
                max_length=20,
            ),
        ),
    ]
