# Generated by Django 4.1.7 on 2023-04-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_objective_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="attack",
            name="target_profile_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
