# Generated by Django 4.1.7 on 2023-04-10 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_attack_target_profile_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attacklog",
            name="attack",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="core.attack",
            ),
        ),
        migrations.AlterField(
            model_name="phishingemail",
            name="subject",
            field=models.TextField(),
        ),
    ]
