# Generated by Django 4.1.7 on 2023-04-14 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_phishingemail_generation_parameters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attack",
            name="target_profile_data",
        ),
    ]
