# Generated by Django 4.1.7 on 2023-04-18 16:26

from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models


def copy_target_email_field(apps, schema_editor):
    Attack = apps.get_model("core", "Attack")
    for attack in Attack.objects.all():
        # Copy the value from the old field to the new field
        attack.target_email = attack.target.get("email")
        objective = attack.objective
        objective.target_emails = []
        attack.save()
        objective.save()


def append_target_email(apps, schema_editor):
    Objective = apps.get_model("core", "Objective")
    Attack = apps.get_model("core", "Attack")

    for objective in Objective.objects.all():
        for attack in Attack.objects.filter(objective=objective):
            objective.target_emails.append(attack.target_email)
            objective.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_remove_attack_target_profile_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="attack",
            name="target_email",
            field=models.EmailField(max_length=255, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objective",
            name="target_emails",
            field=ArrayField(models.EmailField(), default=[]),
            preserve_default=False,
        ),
        migrations.RunPython(copy_target_email_field),
        migrations.RemoveField(
            model_name="attack",
            name="target",
        ),
        migrations.AlterField(
            model_name="attack",
            name="target_email",
            field=models.EmailField(max_length=255, null=False),
        ),
        migrations.RunPython(append_target_email),
        migrations.AlterField(
            model_name="objective",
            name="target_emails",
            field=ArrayField(models.EmailField(blank=False), blank=False),
        ),
    ]
