# Generated by Django 4.1.7 on 2023-04-24 10:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0026_remove_attack_unique_ongoing_attack_on_target_email_in_org_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attacklog",
            name="type",
            field=models.CharField(
                choices=[
                    ("CREDENTIALS_SUBMITTED", "Credentials Submitted"),
                    ("EMAIL_SENT", "Email Sent"),
                    ("EMAIL_OPENED", "Email Opened"),
                    ("LINK_CLICKED", "Link Clicked"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="objective",
            name="goal",
            field=models.CharField(
                choices=[
                    ("CREDENTIALS", "Credentials"),
                    ("TARGET_CLICKED_ON_LINK", "Target Clicked On Link"),
                ],
                db_index=True,
                default="CREDENTIALS",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="PhishingTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=200,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                ("token_consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("CREDENTIALS", "Credentials")], max_length=200
                    ),
                ),
                (
                    "attack_artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.attackartifact",
                    ),
                ),
            ],
            options={
                "db_table": "attack_service_phishing_tokens",
            },
        ),
    ]
