## NOTE: this is only for local development.

version: "3"
services:
  test-database:
    image: postgres:15.1
    container_name: attack-service-test-database
    ports:
      - "5432:5432"
    environment:
      PGUSER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./temp/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
