/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The host name or IP address of the PostgreSQL server
 */
export type Host = string;
/**
 * The port number of the PostgreSQL server
 */
export type PortNumber = number;
/**
 * The name of the database to connect to
 */
export type DatabaseName = string;
/**
 * The username to connect as
 */
export type Username = string;
/**
 * The password to connect with
 */
export type Password = string;
/**
 * The schema to use
 */
export type Schema = string;
/**
 * Whether to use SSL to connect to the server
 */
export type UseSSL = boolean;

export interface PostgreSQLConfiguration {
  host: Host;
  port: PortNumber;
  database: DatabaseName;
  user: Username;
  password: Password;
  schema: Schema;
  ssl?: UseSSL;
}
