/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Your Snowflake account identifier.
 */
export type Account = string;
/**
 * The user name to use for authentication.
 */
export type User = string;
/**
 * The password to authenticate with.
 */
export type Password = string;
/**
 * The name of the warehouse to use.
 */
export type Warehouse = string;
/**
 * The name of the application connecting to Snowflake.
 */
export type Application = string;
/**
 * The name of the database to use.
 */
export type Database = string;
/**
 * The name of the schema to use.
 */
export type Schema = string;

export interface SnowflakeConfiguration {
  account: Account;
  user: User;
  password: Password;
  warehouse: Warehouse;
  application?: Application;
  database: Database;
  schema?: Schema;
}
