/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UserFileConfiguration {
  /**
   * Unique identifier
   */
  uuid: string;
  /**
   * Name of the file
   */
  name?: string;
  /**
   * Size in bytes
   */
  size?: number;
}
