# Generated by Django 4.1.5 on 2023-03-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile_data", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="individual",
            old_name="role",
            new_name="role_title",
        ),
    ]
