# Generated by Django 4.1.5 on 2023-03-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_data", "0002_rename_role_individual_role_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="domain",
        ),
        migrations.AddField(
            model_name="organization",
            name="domains",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
