# Generated by Django 4.1.5 on 2023-03-29 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_data", "0003_remove_organization_domain_organization_domains"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="individualhandle",
            name="profile_data_individual_handles_unique_individual_id_type_value",
        ),
        migrations.AddField(
            model_name="individualhandle",
            name="organization",
            field=models.ForeignKey(
                default="64078415-725c-4551-b1fa-233fb19be517",
                on_delete=django.db.models.deletion.CASCADE,
                to="profile_data.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="individualhandle",
            constraint=models.UniqueConstraint(
                fields=("organization", "type", "value"),
                name="profile_data_individual_handles_unique_org_type_value",
            ),
        ),
    ]
