# Generated by Django 4.1.5 on 2023-03-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profile_data",
            "0004_remove_individualhandle_profile_data_individual_handles_unique_individual_id_type_value_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="individualhandle",
            index=models.Index(
                fields=["organization", "type", "value"],
                name="profile_dat_organiz_ccbc29_idx",
            ),
        ),
    ]
